### ISSUE TITLE
Using keys (hash) instead of arrays?

### ISSUE THREAD

**Issue by lancejpollard** [component/set#2]
What do you think about using keys to keep track of the object instead of arrays? This would make for faster lookups.

**Comment by tj** [comment]
I wouldn't worry about it for now, I like that the array gives us a sorted set. For my use-cases at least the sets are usually reasonably small but I think if someone comes across a case where it's actually becoming a bottleneck of some kind we should definitely look into pairing an object/array for faster lookups

**Comment by lancejpollard** [comment]
Cool

**Comment by alekseykulikov** [comment]
FYI: for performance reasons, I implemented hash based https://github.com/gingkoapp/set, which is also ES6 polyfill.
